### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by sol3uk** [HannahSones/WeatherDashboard#1]
**What did you do well?**
- Good design match to guidelines.
- Mobile first & responsive.

**Needs improvement**
- Please remove unnecessary console logs.

**Suggested improvements (Doesn't affect grade)**
- Fix a bug where you can have multiple history results for the same search.
- There is also a small issue with when you press enter to submit the form rather than click on the search box it will submit with the previously searched item. (Look into using the on submit event to handle it and make the button submit the form).

**GRADE:** A
[BCS](https://bootcampspot.com/gradebook/79268/grade/63220)

You can let us know about any changes by tagging us in a comment below using "@".

**Comment by HannahSones** [comment]
@sol3uk console logs removed.
Thank you.
